CREATE TABLE PRODUTO
(
    ID                     VARCHAR(40) PRIMARY KEY NOT NULL,
    NOME                   VARCHAR(80) NOT NULL,
    DESCRICAO              VARCHAR(80) NOT NULL,
    CODIGO_SKU             VARCHAR(80) NOT NULL,
    UNIDADE_COMERCIAL      VARCHAR(4) NOT NULL,
    MARCA_ID               VARCHAR(40) NOT NULL,
    ATIVO                  BIT NOT NULL,
    USA_CONTROLE_DE_LOTE   BIT NOT NULL,
    CODIGO_DE_BARRAS       VARCHAR(40) NOT NULL,
    PRECO_VENDA            DECIMAL(15, 2) NOT NULL,
    DATA_CADASTRO          DATETIME,
    DATA_ATUALIZACAO       DATETIME,

    CONSTRAINT FK_MARCA_PRODUTO FOREIGN KEY (MARCA_ID) REFERENCES MARCA(ID)
);