CREATE TABLE PRODUTO_CATEGORIA (
    PRODUTO_ID VARCHAR(40) NOT NULL,
    CATEGORIA_ID VARCHAR(40) NOT NULL,

    CONSTRAINT FK_PRODUTO_PRD_CAT FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO (ID),
    CONSTRAINT FK_CATEGORIA_PRD_CAT FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID)
);